$serverinstall = <<-'SCRIPT'
sudo yum -y update
sudo yum install -y nfs-utils nano firewalld
sudo mkdir -p /var/nfsshare
sudo chmod -R 755 /var/nfsshare
sudo chown nfsnobody:nfsnobody /var/nfsshare
sudo systemctl enable rpcbind
sudo systemctl enable nfs-server
sudo systemctl enable nfs-lock
sudo systemctl enable nfs-idmap
sudo systemctl start rpcbind
sudo systemctl start nfs-server
sudo systemctl start nfs-lock
sudo systemctl start nfs-idmap
echo "/var/nfsshare    192.168.56.101(rw,sync,no_root_squash,no_all_squash)" | sudo tee /etc/exports
echo "/home            192.168.56.101(rw,sync,no_root_squash,no_all_squash)" | sudo tee -a /etc/exports
sudo systemctl restart nfs-server nfs-lock nfs-idmap
sudo systemctl enable firewalld
sudo systemctl start firewalld
sudo firewall-cmd --permanent --zone=public --add-service=nfs
sudo firewall-cmd --permanent --zone=public --add-service=mountd
sudo firewall-cmd --permanent --zone=public --add-service=rpc-bind
sudo firewall-cmd --reload
SCRIPT

$clientinstall = <<-'SCRIPT'
sudo yum -y update
sudo yum install -y nfs-utils nano
sudo mkdir -p /mnt/nfs/home
sudo mkdir -p /mnt/nfs/var/nfsshare
sudo mount -t nfs 192.168.56.100:/home         /mnt/nfs/home
sudo mount -t nfs 192.168.56.100:/var/nfsshare /mnt/nfs/var/nfsshare
echo "192.168.56.100:/home    /mnt/nfs/home   nfs defaults 0 0" | sudo tee /etc/fstab
echo "192.168.56.100:/var/nfsshare    /mnt/nfs/var/nfsshare   nfs defaults 0 0" | sudo tee -a /etc/fstab
df -kh
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    if Vagrant.has_plugin?("vagrant-vbguest") then
      server.vbguest.auto_update = false
      server.vbguest.installer_options = { allow_kernel_upgrade: true }  
    end
    server.vm.synced_folder ".", "/vagrant", type: "rsync"
    server.vm.network "private_network", ip: "192.168.56.100"
    server.vm.provision "shell", inline: $serverinstall
  end
  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "client"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    if Vagrant.has_plugin?("vagrant-vbguest") then
      client.vbguest.auto_update = false
      client.vbguest.installer_options = { allow_kernel_upgrade: true }  
    end
    client.vm.synced_folder ".", "/vagrant", type: "rsync"
    client.vm.network "private_network" , ip: "192.168.56.101"
    client.vm.provision "shell", inline: $clientinstall
  end
end